name: Render PlantUML Diagrams

on:
  push:
    paths:
      - '**/*.puml'
  pull_request:
    paths:
      - '**/*.puml'

jobs:
  render-diagrams:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Render PlantUML diagrams
        uses: grassedge/plantuml-action@v1
        with:
          args: -tsvg
          
      - name: Commit rendered diagrams
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git diff --staged --quiet || git commit -m "Auto-render PlantUML diagrams [skip ci]"
          git push
